apiVersion: v1
kind: ServiceAccount
metadata:
  name: glpi
  labels:
    app.kubernetes.io/name: glpi
    app.kubernetes.io/instance: glpi-glpi
    app.kubernetes.io/version: "9.4.5"
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: glpi
  namespace: glpi
