apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
type: Opaque
data:
  MYSQL_PASSWORD: {{ .Values.mysqlDbPassword | b64enc }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mysqlDbRootPassword | b64enc }}