apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
type: Opaque
data:
  # mariadb_PASSWORD: admin123 / YWRtaW4xMjM=
  MYSQL_PASSWORD: {{  .Values.MysqlDbPassword }}
  {{- if (not .Values.MysqlDbRootPassword) }}
  mariadb-root-password: {{ .Values.MysqlDbRootPassword }}
  {{- else }}
  mariadb-root-password: {{ required "A MariaDB Root Password is required!" .Values.auth.rootPassword | b64enc | quote }}
  {{- end }}
  # MYSQL_ROOT_PASSWORD: {{ .Values.MysqlDbRootPassword }}