apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "glpi.labels" . | nindent 4 }}
data:
  MYSQL_DATABASE: glpi
  MYSQL_USER: glpi
