apiVersion: v1
kind: Secret
metadata:
  name: {{ include "glpi.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "glpi.labels" . | nindent 4 }}
type: Opaque
data:
  # mariadb_PASSWORD: admin123 / YWRtaW4xMjM=
  MYSQL_PASSWORD: {{  .Values.MysqlDbPassword }}
  MYSQL_ROOT_PASSWORD: {{  .Values.MysqlDbRootPassword }}